### ISSUE TITLE
May be a bug about the mask type "c" 

### ISSUE THREAD

**Issue by wsxtyrdd** [lumingzzz/TinyLIC#11]
The mask type "c" corresponds to the situation that the current pixel can be predicted by all the surrounding ones within the kernel, as described in detailed in the paper.

/compressai/layers/layers.py; 
```
class MultistageMaskedConv2d：
        elif mask_type == 'C':
            self.mask[:, :, 0::2, 1::2] = 1
            self.mask[:, :, 1::2, :] = 1
```

The kernel of mask_type C will be:
```
tensor([[0., 1., 0.],
          [1., 1., 1.],
          [0., 1., 0.]])
```

However, it should be:
```
        elif mask_type == 'C':
            self.mask[:, :, 0::2, 1::2] = 1
            self.mask[:, :, :, 0::2] = 1
```
which returns kernel:
```
tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])
```

**Comment by lumingzzz** [comment]
Hi, thank you for your comment. It should be correct as you said when the kernel size was 3x3. However, in this revised version, we changed the kernel size of type "B" and "C" from 3x3 to 5x5 for better performance. Thus the code could be correct for 5x5. Unfortunately, the results did not show improvement by enlarging the kernel size. Maybe 3x3 is sufficient.

**Comment by wsxtyrdd** [comment]
Oh, I just noticed that the kernel size has changed. Thanks for your quickly rely. Have a nice day!
