### ISSUE TITLE
training time and lambda choice

### ISSUE THREAD

**Issue by xuezhongcailian** [lumingzzz/TinyLIC#2]
![image](https://user-images.githubusercontent.com/31470730/168234065-4f984aa2-7b67-4dbf-84cf-73804a8d6ba0.png)
Hello, thank you for your work and open source, I seen it in the paper, how do these values of lamda get, and how long does it take to train a model, thank you

**Comment by lumingzzz** [comment]
Hi,
The lambda values are chosen empirically to simulate wide range bitrate. We directly use the eight values given by CompressAI, you can refer to https://github.com/InterDigitalInc/CompressAI for more details.
It takes about 4 days to train the low-rate models and about 6 days for the high-rate ones using my RTX Titan.
