### ISSUE TITLE
tic or tinylic is not valid argument

### ISSUE THREAD

**Issue by RobinHistory** [lumingzzz/TinyLIC#3]
![JWBT1P4N0EF91RLV3A{E5ZM](https://user-images.githubusercontent.com/36556340/170400534-9a237c23-2170-41ad-9d12-d67a395babf5.png)

I'm new to Compress ai. In the example directory, I followed the instruction  to use  'python examples/train.py -m tinylic -d mydataset/ --epochs 400 -lr 1e-4 --batch-size 8 --cuda --save ' , 'python train.py -m tinylic -d mydataset/ '  , 'python train.py -m tic -d mydataset/' and 'python train.py -d mydataset/'. 
But I always get the same error of tic argument. So I wonder how to train TIC?

**Comment by lumingzzz** [comment]
I made a mistake in command line of installation and another repo (TIC) was cloned by you. I have corrected it and now you can re-clone it. Sorry for my carelessness.

**Comment by RobinHistory** [comment]
![image](https://user-images.githubusercontent.com/36556340/170632994-a321d4ba-4cc3-4ad2-8d0f-601e2b557cd3.png)
I re-clone the repo and try to train again. But a new import error seems like this.

**Comment by lumingzzz** [comment]
You can now use "tinylic" instead of "tic" as the model for training.

**Comment by RobinHistory** [comment]
No matter I use 'tinylic' or 'tic', the import error is always there like cannot import 'tic'.

**Comment by lumingzzz** [comment]
Oh, I see. You should remove line 37 and 50 in zoo/__init__.py or re-clone the repo, I have updated it.

**Comment by RobinHistory** [comment]
Thanks for your answer, now everything works well.
