### ISSUE TITLE
Crop size is larger than image size.

### ISSUE THREAD

**Issue by RobinHistory** [lumingzzz/TinyLIC#4]
You mentioned you used the Flicker dataset for training, but not all the image size is bigger than the crop size(256x256).
So I wonder where  the padding codes I should add to, or you have other methods to handle the image size?

**Comment by lumingzzz** [comment]
You can directly remove those images with size less than 256x256 as in [script](https://github.com/xyq7/InvCompress/tree/main/codes/scripts).
