### ISSUE TITLE
Maybe a bug(wrong slice) in layers.py.

### ISSUE THREAD

**Issue by RobinHistory** [lumingzzz/TinyLIC#5]
/compressai/layers/layers.py  
line 100;     self.mask[:, :, 1:2, 1:2] = 0
Do you mean self.mask[:, :, 1::2, 1::2] = 0  ?
If you use the mask, I think here should be one more ":" here.

**Comment by lumingzzz** [comment]
There is nothing wrong here. The mask type "c" corresponds to the situation that the current pixel can be predicted by all the surrounding ones within the kernel, as described in detailed in the paper.

**Comment by RobinHistory** [comment]
I already check the paper. If the  mask matrix is in the fixed shape 3x3, it's right.
