### ISSUE TITLE
Broken link for pretrained weight

### ISSUE THREAD

**Issue by JoeK6279** [lumingzzz/TinyLIC#7]
Hello, thank you for the work and code release.
However, the [link](https://box.nju.edu.cn/d/20d8c218821d48d6af23/) to the pretrained model weight doesn't work, a connection timed out occurs when I tried to reach the site.
Could you update the link or possibliy upload the weights to other file sharing site (such as google drive)?
On this matter, is it possible to also release weights of other rate points (like one of the higher rates)?
Thank you.

**Comment by lumingzzz** [comment]
Hi, 
the school's external port has been blocked recent days due to the party meeting. It will be accessible at the end of the month. In addition, we have an updated version of our work and will upload them all as soon as possible.

**Comment by lumingzzz** [comment]
Hi,
the latest version of our model is released, and you can download all the 8 models using the link (https://box.nju.edu.cn/d/6bd0aafa2faf47cab7c2/) now.

**Comment by JoeK6279** [comment]
Thank you for the update.
