### ISSUE TITLE
关于数据的问题

### ISSUE THREAD

**Issue by guoguo1314** [lumingzzz/TinyLIC#8]
您好，博主，请问您画率失真图Balle，Minnen，Cheng，xie，BPG, VVC数据是从哪儿来的？谢谢博主了。

**Comment by lumingzzz** [comment]
大部分可以用他们release出来的模型测试，compressai的github库也有一些数据。

**Comment by guoguo1314** [comment]
您使用的训练集，验证集分别多少张图片？我想自己跑一跑实验，不知道用多少合适。
