### ISSUE TITLE
Parameter Error in tinylic.py Multiplexer and Demultiplexer

### ISSUE THREAD

**Issue by RobinHistory** [lumingzzz/TinyLIC#9]
In tinylic.py,
from line 690:
`y_slice_anchor, y_slice_non_anchor = Demultiplexer(y_slice)`
line 698,699:
  `scales_hat_anchor, _ = Demultiplexer(scales_hat)
                means_hat_anchor, _ = Demultiplexer(means_hat)`
line 707:
`y_hat_slice = Multiplexer(y_hat_slice_anchor, torch.zeros_like(y_hat_slice_anchor))`
The two functions need four parameters with only two given.
Same error happens after these lines in the similar parts.
Can you fix it? Thanks!

**Comment by lumingzzz** [comment]
Have you updated the whole repo including the model and utils? I didn't meet this problem from my side.

**Comment by RobinHistory** [comment]
Ohh, I see.  I use the old version of the utils.py.
Thanks.
